### ISSUE TITLE
Is using lob.py enough?

### ISSUE THREAD

**Issue by cofibit** [Crypto-toolbox/HFT-Orderbook#18]
Thanks for your implementation on this one, I looking at integrating it on my python based trading algorithm and would like to ask if just by using lob.py will suffice to use your orderbook? Or do I have to compile C implementation keep it running on the background? 

TIA

**Comment by nlsdfnbch** [comment]
The C implementation is fully tested and working as expected - the python implementation, however, is not. I recommend using the C implementation.

**Comment by cofibit** [comment]
Have you got some samples in C on how to consume your orderbook implementation?

**Comment by cofibit** [comment]
@tcccapinfo cool e-mail me at arvindacumos@gmail.com thanks

**Comment by wardbradt** [comment]
@tcccapinfo I am also trying to understand how to use this. If I have `Limit *root` as the root of the tree, and I want to add `Order* order` to the tree, how do I do so? I believe I have to use `pushOrder(Limit *limit, Order *newOrder)` but how do I get `limit` (the `Limit` where `limitPrice` == `newOrder->limit`? Does it require an additional function to iterate through the tree and find `limit`? My email is wardbradt5@gmail.com if email is preferred.
